### PR TITLE
Added support for YouTube Music (+PhpStorm+JetBrainsIDE)

### PR DESCRIPTION
**Pull request by Zo-Bro-23**
- Updated ```allowListGames.js``` with all lowercase
- Updated ```index.js``` to support YouTube Music

### CODE REVIEW

**Comment by zyplos** [comment]
What are you using for YouTube Music that needs special image handling? I don't use YouTube Music so I hadn't considered it here but it's worth adding.

**Comment by Zo-Bro-23** [comment]
I'm using the YouTube Music desktop app by @th-ch ([th-ch/youtube-music](https://github.com/th-ch/youtube-music)). It has a Discord plugin which connects to Discord to display the current song as the user's presence. The ```largeImage``` tag shows an ```mp:external``` tag, so I added code to parse that into a URL that the program can understand.

**Comment by zyplos** [comment]
This mp prefix thing seems to be something they added and I had no idea. This new image logic could be used in general if any other application uses it. Noted it in #9, but for now with this merge request:

Could you add a condition to only use that image logic with whatever application ID [th-ch/youtube-music](https://github.com/th-ch/youtube-music) uses? #9 can be fixed after this just to close this pull request.

**Comment by zyplos** [comment]
Actually, I poked around [th-ch/youtube-music](https://github.com/th-ch/youtube-music) and this was easier to fix than I thought. Pushed my own fix that should work for any application that uses external images and not just this one application.

**Comment by Zo-Bro-23** [comment]
It's working! I guess I was overcomplicating things 🥲

**Pull request closed without merging**
